### ISSUE TITLE
PSAT+

### ISSUE THREAD

**Issue by smshariatzadeh** [Sinan81/PSAT#2]
Dear Sinan81

Please find attached file (following link):
[https://drive.google.com/file/d/1qoyhS-xGSq0dx2-jnfxiJwFvcvB15IpY/view?usp=sharing](url)

Some changes and upgrading PSAT 2.1.11 which i have done:

1. short circuit calculations

2. simulink mdl and slx support ( convert simulink library extension from mdl to slx)

3. adding two Icon in program toolbar

4. removing bug in win64 bit  opening report

5. changing setting Icon

6. Changing the layout of icons on the main screen of the program
 
Please review the files and test the program.

Best Regards.

**Comment by Sinan81** [comment]
Can you please add these contributions to your own clone of the repo. Afterwards it can be merged to any other clone easily. Thanks.

**Comment by smshariatzadeh** [comment]
Dear Sinan

I update my psat clone:

https://github.com/smshariatzadeh/PSAT

Please check these files.

**Comment by Sinan81** [comment]
I am not able to review and merge your contributions right now since I don't have Matlab. But that's ok since people can see what's going on different clones via Insights -> Network:

https://github.com/Sinan81/PSAT/network

Now that I think about it may be it would be better to keep 'master' branch same as the original code by F. Milano. however we can create a new branch say `develop` or `psat+`  or `psat-community-develop` to include contributions from the community. That way, it will be crystal clear what deviations were made from the original code.
